import esbuild from "esbuild";
import process from "process";
import { builtinModules as builtins } from "module";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// Path to your Obsidian vault plugin folder for live testing
const vaultPluginDir = "C:\\Obsidian\\Vault 1\\.obsidian\\plugins\\outlook-event-notes";

function copyToVault() {
	if (!fs.existsSync(vaultPluginDir)) return;
	for (const file of ["main.js", "manifest.json", "styles.css"]) {
		try {
			fs.copyFileSync(file, path.join(vaultPluginDir, file));
		} catch (e) {
			console.error(`Failed to copy ${file} to vault:`, e.message);
		}
	}
	console.log("[vault] Copied main.js, manifest.json, styles.css →", vaultPluginDir);
}

const copyPlugin = {
	name: "copy-to-vault",
	setup(build) {
		build.onEnd(() => copyToVault());
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
